In [1]:
import numpy as np

In [6]:
arr = np.array([[1,2,3], [2,3,4]])

In [7]:
print(arr.sum())

15


In [12]:
print(arr.shape)

(2, 3)


In [9]:
arr2 = np.array([1,2,3,4,5])
print(arr2+2)
print(arr2+10)

[3 4 5 6 7]
[11 12 13 14 15]


In [13]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr3.mean())
print(arr3.sum())
print(arr3.max())

5.5
55
10


In [26]:
arr4 = np.array([[1,2,3],[4,5,6]])
print(arr4.shape)
print(arr4[1][1])

print(arr4.reshape(3,2))

(2, 3)
5
[[1 2]
 [3 4]
 [5 6]]


In [17]:
arr21 = np.array([1,2,3,4])
arr22 = np.array([7,8,9,10])

print(arr21)
print(arr22)
print(arr21+arr22)
print(arr21*arr22)
print(arr21**2)

[1 2 3 4]
[ 7  8  9 10]
[ 8 10 12 14]
[ 7 16 27 40]
[ 1  4  9 16]


In [24]:
arr31 = np.array([1, 2, 3, 4, 5, 6])

print(arr31.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [27]:
arr41 = np.array([1, 2, 3, 4, 5, 6])

arr4[arr4 > 3]

array([4, 5, 6])

In [30]:
arr = np.array([5, 10, 15, 20])

result = np.where(arr > 10, arr, 0)

print(result)

[ 0  0 15 20]
